export const VENDOR_PORTAL_URLS: Record<string, string> = {
  AETHER_DYNAMICS: "https://portal.aether-dynamics.com/invoices",
  NEURAL_NETWORKS_INC: "https://billing.neural-networks.io/pending",
  ORBITAL_CARGO_CO: "https://cargo.orbital.co/finance",
  BIO_SYNTH_LABS: "https://payments.biosynthlabs.net",
  ZENITH_SYSTEMS: "https://zenithsystems.com/vendor-portal",
  STELLAR_FINANCE: "https://app.stellarfinance.io/invoices",
  QUANTUM_CORE: "https://quantumcore.tech/billing",
  NOVA_LOGISTICS: "https://novalogistics.eu/payments",
  CYBERDYNE_TECH: "https://cyberdyne.tech/vendor-login",
  PULSAR_ENERGY: "https://pulsarenergy.com/finance",
  HELIX_CORP: "https://billing.helixcorp.net",
  NEXUS_INNOVATIONS: "https://nexusinnovations.com/vendor",
  APEX_DIGITAL: "https://apexdigital.io/invoices",
  TITAN_ROBOTICS: "https://titanrobotics.ai/billing",
  VORTEX_MEDIA: "https://vortexmedia.com/payments",
  SYNAPSE_AI: "https://synapse.ai/vendor-portal",
  KRYPTON_VENTURES: "https://kryptonventures.com/finance",
  OMEGA_SECURITY: "https://omegasecurity.net/billing",
  PRISM_ANALYTICS: "https://prismanalytics.io/vendor",
  FUSION_LABS: "https://fusionlabs.com/payments",
  NEXUS_SUPPLY: "https://nexus-supply.com/invoices",
  AURORA_MATERIALS: "https://auroramaterials.com/vendor-portal",
  PHOENIX_HARDWARE: "https://phoenixhardware.io/billing",
  ECLIPSE_SOFTWARE: "https://eclipsesoftware.dev/finance",
  STRATUM_SERVICES: "https://stratum.services/vendor",
  VERTEX_CONSULTING: "https://vertexconsulting.com/payments",
  HORIZON_LOGISTICS: "https://horizonlogistics.net/invoices",
  MERIDIAN_CLOUD: "https://meridiancloud.com/billing",
  CASCADE_SOLUTIONS: "https://cascadesolutions.tech/vendor",
  IGNITE_HOSTING: "https://ignitehosting.com/finance",
  SPECTRUM_TELECOM: "https://spectrumtelecom.net/payments",
  FLUX_UTILITIES: "https://fluxutilities.com/invoices",
  POLARIS_RENTALS: "https://polarisrentals.io/billing",
  ECHO_MARKETING: "https://echomarketing.co/vendor-portal",
  RADIX_HARDWARE: "https://radixhardware.com/payments",
  TYCHO_SHIPPING: "https://tychoshipping.net/finance",
  LUMEN_ENERGY: "https://lumenenergy.com/vendor",
  AXIS_FINANCIAL: "https://axisfinancial.io/invoices",
  NEBULA_INSURANCE: "https://nebulainsurance.com/billing",
  DYNAMO_RECRUIT: "https://dynamorecruit.net/payments",
};

export function getVendorPortalUrl(vendorName: string): string | undefined {
  return VENDOR_PORTAL_URLS[vendorName];
}
